### ISSUE TITLE
Sign up error in the website.

### ISSUE THREAD

**Issue by vignesh1507** [rakshitkapoor/Snap-n-Score#1]
<img width="1440" alt="Screenshot 2024-10-09 at 11 29 36 PM" src="https://github.com/user-attachments/assets/29f17b55-40b0-44a2-8373-5e7dddcc4161">

**Comment by rakshitkapoor** [comment]
Vignesh the website only takes emails with bennett.edu.in ending as the website is for teachers to generate the QR code.
To replicate the project signup on the app as a 2nd year, and login on the website with the following test values.
Email: rajnish@bennett.edu.in
Password: 123456

**Comment by vignesh1507** [comment]
oh ok, sure got it.
